#!/bin/bash
LOG_FILE="/tmp/updates.log"
exp_dir="$HOME/.local/bin"
exec > >(tee -a "$LOG_FILE") 2>&1
###
# Ensure ~/.local/bin is in PATH
###
if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
    echo "Adding to PATH"
    echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
    source ~/.bashrc  # Reload for current shell
    cp "$0" "$exp_dir"/
fi
# Set colors
green='\033[0;32m'
yellow='\033[0;33m'
red='\033[0;31m'
nc='\033[0m' # No Color

# Update Arch repositories and keyrings
echo -e "${green}Updating Arch repositories and keyrings...${nc}"
sudo pacman -Syy || { echo -e "${red}Error updating repositories!${nc}"; exit 1; }

# Update pacman packages
echo -e "${green}Updating pacman packages...${nc}"
sudo pacman -Syu --noconfirm || { echo -e "${red}Error updating pacman packages!${nc}"; exit 1; }

#not working? Try this:
#sudo pacman -Sy endeavouros-keyring --noconfirm
#sudo pacman -Sy archlinux-keyring --noconfirm

# Update yay packages (requires yay to be installed)
echo -e "${green}Updating yay packages...${nc}"
if command -v yay &> /dev/null; then
  yay -Syu --noconfirm || { echo -e "${red}Error updating yay packages!${nc}"; exit 1; }
else
  echo -e "${yellow}yay not found. Installing yay...${nc}"
  sudo pacman install yay --noconfirm || { echo -e "${red}Couldn't install yay. Wtf?${nc}"; exit 1; }
fi

# Update Flatpak
echo -e "${green}Updating Flatpak...${nc}"
flatpak update --assumeyes || { echo -e "${red}Error updating Flatpak!${nc}"; exit 1; }

# Update yt-dlp
echo -e "${green}Updating yt-dlp....${nc}"
yt-dlp --update || { echo -e "${red}Error updating Flatpak!${nc}"; exit 1; }

# Cleanup and final message
echo -e "${green}System update complete.${nc}"
