#!/bin/bash
#the following two are only necessary on a fresh install:
#sudo pacman --noconfirm -Syyu flatpak yay
#yay --noconfirm -Syyu fastfetch ffmpeg mpv ani-cli yt-dlp scrcpy
#Arch updates:
yay --noconfirm -Syyu
echo "Updating yt-dlp."
/home/igel/.local/bin/yt-dlp --update #> /dev/null
echo "Checking if Flathub repository is missing..."
if ! flatpak remote-list | grep -q flathub; then
    echo "Flathub not found - adding repository..."
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    echo "Flathub repository added successfully."
else
    echo "Flathub repository already configured."
fi
echo "Checking if some flatpaks are missing..."
flatpaks=(
    "Firefox"
    "Protontricks"
    "Flatseal"
    "Spotify"
    "SGDBoop"
    "Bottles"
    "Steam"
    "VSCodium"
    "Quick Web Apps"
    "Komikku"
    "Hedge Mod Manager"
    "Ryujinx (Ryubing)"
    "Kooha"
    "Upscaler"
    "Lutris"
    "Luanti"
    "Scribus"
    "Dolphin Emulator"
    "Audacious"
    "Audacity"
    "Azahar"
    "Grabber"
    "Cheese"
    "Pika Backup"
    "JDownloader"
    "Krita"
    "KeePassXC"
    "LibreOffice"
    "PPSSPP"
    "qBittorrent"
    "Signal Desktop"
)

for flatpak_name in "${flatpaks[@]}"; do
    if ! flatpak list --app --columns=name | grep -qxF "$flatpak_name"; then
        app_id=$(flatpak search "$flatpak_name" --columns=name,application | \
                 awk -v name="$flatpak_name" '$1 == name {print $2; exit}')

        if [[ -n "$app_id" ]]; then
            echo "Installing '$flatpak_name'..."
            flatpak install --user flathub "$app_id" -y >/dev/null 2>&1
            echo "Installed: $flatpak_name ($app_id)"
        else
            echo "Error: Could not find '$flatpak_name' on Flathub"
        fi
    fi
done
#Flatpak updates:
echo "Updating flatpaks."
flatpak update -y
echo "Updates complete."
