#!/bin/bash
###
#Ubuntu apt updates:
###
quiet-update() {
    # Silent update check
    sudo apt update -y >/dev/null 2>&1

    # Check if updates exist
    if [ $(apt list --upgradable 2>/dev/null | wc -l) -gt 1 ]; then
        echo "Updates available:"
        apt list --upgradable 2>/dev/null | grep -v '^Listing...'
        sudo apt upgrade -y --allow-downgrades 2>&1 | grep -v '^Summary:\|^WARNING\|^$'
    else
        echo "System up to date"
    fi
}
sudo apt autoremove -y 
###
#Install missing apt packages:
###
for pkg in steam-devices adb ffmpeg ani-cli syncplay fastfetch mpv snapd flatpak plasma-discover-backend-snap plasma-discover-backend-flatpak; do
    if ! dpkg -s "$pkg" >/dev/null 2>&1; then
        sudo apt install -y "$pkg" >/dev/null 2>&1
    fi
done
###
#Install latest yt-dlp version:
###
if [ ! -f ~/.local/bin/yt-dlp ]; then
    wget -O ~/.local/bin/yt-dlp https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp > /dev/null 2>&1
    chmod a+rx ~/.local/bin/yt-dlp > /dev/null 2>&1
fi
if apt list --installed 2>/dev/null | grep -q "^yt-dlp/"; then
    sudo apt remove -y yt-dlp >/dev/null 2>&1
fi
echo "Updating yt-dlp."
yt-dlp --update | sed -n '/yt-dlp is up to date/s/(.*//p' | sed 's/\.$//' || true
###
#Install missing snap packages:
###
for snap in discord scrcpy; do
    snap list "$snap" >/dev/null 2>&1 || sudo snap install "$snap" >/dev/null 2>&1
done
###
#Update flatpaks and snaps:
###
echo "Updating snaps."
sudo snap refresh
echo "Updating flatpaks."
if output=$(flatpak update -y 2>&1); then
    filtered=$(grep -v -e '^Info:' -e '^   ' -e '^$' <<< "$output")
    [[ "$filtered" =~ "Nothing to do" ]] && echo "All flatpaks up to date." || echo "$filtered"
fi
###
#Check for major distro-upgrades:
###
pending_pkg=$(sudo apt-get -s dist-upgrade | grep -P '^\d+ (removed|newly installed)')
if [[ -n "$pending_pkg" ]]; then
    echo "Major package changes required:"
    sudo apt-get -s dist-upgrade | grep -P '^\d+ (upgraded|newly installed|removed)'
    read -p "Continue? [y/N] " -n 1 -r
    echo
    [[ $REPLY =~ ^[Yy]$ ]] && sudo apt-get dist-upgrade
fi
# Check for release upgrades
if sudo do-release-upgrade -c >/dev/null; then
    echo "New OS release available!"
    read -p "Upgrade release? [y/N] " -n 1 -r
    echo
    [[ $REPLY =~ ^[Yy]$ ]] && sudo do-release-upgrade
fi
echo "Updates complete."
